/*
 * Generated by XDoclet - Do not edit!
 */
package com.mockrunner.example.jms.interfaces;

/**
 * Home interface for PrintSession.
 */
public interface PrintSessionHome
   extends jakarta.ejb.EJBHome
{
   String COMP_NAME="java:comp/env/ejb/PrintSession";
   String JNDI_NAME="com/mockrunner/example/PrintSession";

   com.mockrunner.example.jms.interfaces.PrintSession create()
      throws jakarta.ejb.CreateException,java.rmi.RemoteException;

}
